"""
Catálogo de cuentas contables — El Cuadre Frío, C.A.
Manufacturera de alimentos congelados · VEN-NIF PYME · Costeo por Absorción

MÉTODO DE INVENTARIO: Perpetuo (continuo) con valoración a PROMEDIO PONDERADO.
  - Las cuentas de inventario (MP, PEP, PT) son cuentas VIVAS de saldo permanente.
  - El kardex (MovimientoInventario) es el auxiliar; las cuentas 1.1.2x el control.
  - Cada venta genera el asiento de costo automático: Debe 5.2.0x / Haber 1.1.22.0x.

Cambios estructurales vs. versión anterior:
  - Costo de Ventas movido a subgrupo 5.2 con una cuenta por SKU (5.2.01–05).
  - Inventario PT VIVO por SKU (1.1.22.01–05); se eliminó "Inicial/Final" como
    cuentas de mayor (pasan a ser snapshots del Libro de Inventarios).
  - MP/PEP: una sola cuenta viva (1.1.20.01 / 1.1.21.01).

Cuentas nuevas solicitadas por la cátedra:
  - 5.1.22  Mermas Normales de Producción       (costo absorbible)
  - 6.6.01  Pérdida por Cadena de Frío           (pérdida ANORMAL → resultados)
  - 4.1.0x.01/.02  Ventas por canal Mayor/Detal  (auxiliares por SKU)
  - 4.1.06.01/.02  Devoluciones Normales / por Productos Dañados

Formato de cada tupla:
  (codigo, nombre, tipo, naturaleza, estado_financiero, subcategoria)
"""

CATALOGO_DEFAULT = [


    ("1",         "ACTIVOS",                                                    "Grupo",     "",          "",                       ""),
    ("1.1",       "ACTIVO CORRIENTE",                                           "Subgrupo",  "",          "",                       "Activo Corriente"),
    ("1.1.01",    "Caja",                                                       "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.02",    "Caja Chica",                                                 "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.03",    "Banco — Cta. Cte. BDV",                                      "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.04",    "Banco — Cta. Cte. Mercantil",                                "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.05",    "Banco — Cuenta de Ahorros",                                  "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.06",    "Banco — Cuenta en Divisas (USD)",                            "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.10",    "Cuentas por Cobrar — Clientes",                              "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.11",    "Cuentas por Cobrar — Otras",                                 "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.12",    "Provisión Cuentas Incobrables",                              "Cuenta",    "Acreedora", "Situación Financiera",   "Activo Corriente"),
    ("1.1.15",    "IVA Crédito Fiscal",                                         "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.16",    "Retenciones de IVA por Recuperar",                           "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.17",    "Retenciones de ISLR por Recuperar",                          "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.18",    "Otros Créditos Fiscales por Recuperar",                      "Subgrupo",  "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.18.01", "IVA Crédito Fiscal por Recuperar",                           "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.18.02", "ISLR por Recuperar — Compras",                               "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.18.03", "Retenciones IVA por Recuperar — Ventas",                     "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.18.04", "Fondo Protección Pensiones — Aporte Retenido",               "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.20",    "INVENTARIO DE MATERIA PRIMA",                                "Subgrupo",  "",          "Situación Financiera",   "Activo Corriente"),
    ("1.1.20.01", "Inventario de Materia Prima",                                "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.21",    "INVENTARIO DE PRODUCTOS EN PROCESO",                         "Subgrupo",  "",          "Situación Financiera",   "Activo Corriente"),
    ("1.1.21.01", "Inventario de Productos en Proceso",                         "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.22",    "INVENTARIO DE PRODUCTOS TERMINADOS",                         "Subgrupo",  "",          "Situación Financiera",   "Activo Corriente"),
    ("1.1.22.01", "Inventario PT — TQ-30/50 Tequeños Clásicos",                 "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.22.02", "Inventario PT — MP-15 Minipizzas Surtidas",                  "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.22.03", "Inventario PT — MF-500 Masa Fácil Hojaldre",                 "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.22.04", "Inventario PT — TJ-20 Tequeños Jumbo",                       "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.22.05", "Inventario PT — PS-20/30 Pastelitos Rellenos",               "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.25",    "Materiales y Suministros de Planta",                         "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.26",    "Insumos Industriales — EPP y Limpieza",                      "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.30",    "Gastos Pagados por Anticipado",                              "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.31",    "Seguros Pagados por Anticipado",                             "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.32",    "Anticipos a Proveedores",                                    "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.1.40",    "Aporte Fondo Pensiones por Recuperar",                       "Cuenta",    "Deudora",   "Situación Financiera",   "Activo Corriente"),
    ("1.2",       "ACTIVO NO CORRIENTE",                                        "Subgrupo",  "",          "",                       "Activo No Corriente"),
    ("1.2.01",    "Terrenos",                                                   "Cuenta",    "Deudora",   "Situación Financiera",   "Activo No Corriente"),
    ("1.2.02",    "Edificio / Planta de Producción",                            "Cuenta",    "Deudora",   "Situación Financiera",   "Activo No Corriente"),
    ("1.2.03",    "Depreciación Acum. — Edificio",                              "Cuenta",    "Acreedora", "Situación Financiera",   "Activo No Corriente"),
    ("1.2.05",    "Maquinaria y Equipos de Producción",                         "Cuenta",    "Deudora",   "Situación Financiera",   "Activo No Corriente"),
    ("1.2.06",    "Depreciación Acum. — Maquinaria",                            "Cuenta",    "Acreedora", "Situación Financiera",   "Activo No Corriente"),
    ("1.2.08",    "Equipos de Refrigeración / Congelación",                     "Cuenta",    "Deudora",   "Situación Financiera",   "Activo No Corriente"),
    ("1.2.09",    "Depreciación Acum. — Refrigeración",                         "Cuenta",    "Acreedora", "Situación Financiera",   "Activo No Corriente"),
    ("1.2.10",    "Vehículos de Distribución",                                  "Cuenta",    "Deudora",   "Situación Financiera",   "Activo No Corriente"),
    ("1.2.11",    "Depreciación Acum. — Vehículos",                             "Cuenta",    "Acreedora", "Situación Financiera",   "Activo No Corriente"),
    ("1.2.12",    "Equipos de Cómputo",                                         "Cuenta",    "Deudora",   "Situación Financiera",   "Activo No Corriente"),
    ("1.2.13",    "Depreciación Acum. — Cómputo",                               "Cuenta",    "Acreedora", "Situación Financiera",   "Activo No Corriente"),
    ("1.2.15",    "Mobiliario y Enseres",                                       "Cuenta",    "Deudora",   "Situación Financiera",   "Activo No Corriente"),
    ("1.2.16",    "Depreciación Acum. — Mobiliario",                            "Cuenta",    "Acreedora", "Situación Financiera",   "Activo No Corriente"),
    ("1.2.20",    "Activos Intangibles — Marcas y Patentes",                    "Cuenta",    "Deudora",   "Situación Financiera",   "Activo No Corriente"),
    ("1.2.21",    "Amortización Acum. — Intangibles",                           "Cuenta",    "Acreedora", "Situación Financiera",   "Activo No Corriente"),

    ("2",         "PASIVOS",                                                    "Grupo",     "",          "",                       ""),
    ("2.1",       "PASIVO CORRIENTE",                                           "Subgrupo",  "",          "",                       "Pasivo Corriente"),
    ("2.1.01",    "Cuentas por Pagar — Proveedores MP",                         "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.02",    "Cuentas por Pagar — Proveedores Servicios",                  "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.05",    "IVA Débito Fiscal",                                          "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.06",    "Retenciones de IVA por Enterar",                             "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.07",    "Retenciones de ISLR por Enterar",                            "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.08",    "Retenciones de IGTF por Enterar",                            "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.09",    "Impuesto Municipal (IAE) por Pagar",                         "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.10",    "Nómina por Pagar",                                           "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.11",    "Retenciones y Aportes por Pagar",                            "Subgrupo",  "",          "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.11.01", "IVSS — Aporte Patronal y Obrero",                            "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.11.02", "BANAVIH / LVH — Aporte por Pagar",                           "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.12",    "Protección Pensiones por Pagar — Patronal",                  "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.13",    "INCES por Pagar",                                            "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.14",    "IGTF Percibido por Enterar",                                 "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.15",    "Provisión para Utilidades",                                  "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.16",    "Provisión para Vacaciones",                                  "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.17",    "Provisión para Bono Vacacional",                             "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.18",    "Prestaciones Sociales — Fideicomiso",                        "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.20",    "Anticipos de Clientes",                                      "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.21",    "IGTF por Enterar — Cobros en Divisas",                       "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.22",    "Retención Protección Pensiones — Empleados",                 "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.23",    "Otras Retenciones de Nómina",                                "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.25",    "Préstamos Bancarios — Corto Plazo",                          "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.30",    "ISLR por Pagar",                                             "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.35",    "Dividendos por Pagar",                                       "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.40",    "Alquiler Planta por Pagar",                                  "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.41",    "Alquiler Depósito/Distribución por Pagar",                   "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.1.42",    "Alquiler Oficinas Administrativas por Pagar",                "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo Corriente"),
    ("2.2",       "PASIVO NO CORRIENTE",                                        "Subgrupo",  "",          "",                       "Pasivo No Corriente"),
    ("2.2.01",    "Préstamos Bancarios — Largo Plazo",                          "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo No Corriente"),
    ("2.2.05",    "Obligaciones por Arrendamiento Financiero",                  "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo No Corriente"),
    ("2.2.10",    "Préstamos de Accionistas",                                   "Cuenta",    "Acreedora", "Situación Financiera",   "Pasivo No Corriente"),

    ("3",         "PATRIMONIO",                                                 "Grupo",     "",          "",                       ""),
    ("3.1.01",    "Capital Social",                                             "Cuenta",    "Acreedora", "Situación Financiera",   "Patrimonio"),
    ("3.1.02",    "Reserva Legal",                                              "Cuenta",    "Acreedora", "Situación Financiera",   "Patrimonio"),
    ("3.1.03",    "Reserva Estatutaria",                                        "Cuenta",    "Acreedora", "Situación Financiera",   "Patrimonio"),
    ("3.1.04",    "Ajuste por Inflación — Patrimonio",                          "Cuenta",    "Acreedora", "Situación Financiera",   "Patrimonio"),
    ("3.1.05",    "Utilidades Retenidas de Ejercicios Anteriores",              "Cuenta",    "Acreedora", "Situación Financiera",   "Patrimonio"),
    ("3.1.06",    "Pérdidas Acumuladas",                                        "Cuenta",    "Deudora",   "Situación Financiera",   "Patrimonio"),
    ("3.1.07",    "Utilidad / Pérdida del Ejercicio Actual",                    "Cuenta",    "Acreedora", "Situación Financiera",   "Patrimonio"),
    ("3.1.08",    "REI — Reexpresión por Inflación",                            "Cuenta",    "Acreedora", "Situación Financiera",   "Patrimonio"),

    ("4",         "INGRESOS",                                                   "Grupo",     "",          "",                       ""),
    ("4.1",       "INGRESOS OPERACIONALES",                                     "Subgrupo",  "",          "",                       "Ingresos Operacionales"),
    ("4.1.01",    "Ventas — TQ-30/50 Tequeños Clásicos",                        "Subgrupo",  "",          "",                       "Ingresos Operacionales"),
    ("4.1.01.01", "Ventas TQ-30/50 Tequeños Clásicos — Canal Mayor",            "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.01.02", "Ventas TQ-30/50 Tequeños Clásicos — Canal Detal",            "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.02",    "Ventas — MP-15 Minipizzas Surtidas",                         "Subgrupo",  "",          "",                       "Ingresos Operacionales"),
    ("4.1.02.01", "Ventas MP-15 Minipizzas Surtidas — Canal Mayor",             "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.02.02", "Ventas MP-15 Minipizzas Surtidas — Canal Detal",             "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.03",    "Ventas — MF-500 Masa Fácil Hojaldre",                        "Subgrupo",  "",          "",                       "Ingresos Operacionales"),
    ("4.1.03.01", "Ventas MF-500 Masa Fácil Hojaldre — Canal Mayor",            "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.03.02", "Ventas MF-500 Masa Fácil Hojaldre — Canal Detal",            "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.04",    "Ventas — TJ-20 Tequeños Jumbo",                              "Subgrupo",  "",          "",                       "Ingresos Operacionales"),
    ("4.1.04.01", "Ventas TJ-20 Tequeños Jumbo — Canal Mayor",                  "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.04.02", "Ventas TJ-20 Tequeños Jumbo — Canal Detal",                  "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.05",    "Ventas — PS-20/30 Pastelitos Rellenos",                      "Subgrupo",  "",          "",                       "Ingresos Operacionales"),
    ("4.1.05.01", "Ventas PS-20/30 Pastelitos Rellenos — Canal Mayor",          "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.05.02", "Ventas PS-20/30 Pastelitos Rellenos — Canal Detal",          "Cuenta",    "Acreedora", "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.06",    "Devoluciones en Ventas",                                     "Subgrupo",  "",          "",                       "Ingresos Operacionales"),
    ("4.1.06.01", "Devoluciones en Ventas — Normales",                          "Cuenta",    "Deudora",   "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.06.02", "Devoluciones en Ventas — por Productos Dañados",             "Cuenta",    "Deudora",   "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.1.07",    "Descuentos en Ventas",                                       "Cuenta",    "Deudora",   "Estado de Resultado",    "Ingresos Operacionales"),
    ("4.2",       "OTROS INGRESOS",                                             "Subgrupo",  "",          "",                       "Otros Ingresos"),
    ("4.2.01",    "Intereses Ganados",                                          "Cuenta",    "Acreedora", "Estado de Resultado",    "Otros Ingresos"),
    ("4.2.02",    "Ganancia en Venta de Activos",                               "Cuenta",    "Acreedora", "Estado de Resultado",    "Otros Ingresos"),
    ("4.2.03",    "Ingresos Varios",                                            "Cuenta",    "Acreedora", "Estado de Resultado",    "Otros Ingresos"),
    ("4.2.04",    "Ganancia en Diferencial Cambiario",                          "Cuenta",    "Acreedora", "Estado de Resultado",    "Otros Ingresos"),
    ("4.3.01",    "Ganancia Monetaria por Inflación (REI)",                     "Cuenta",    "Acreedora", "Estado de Resultado",    "Ajuste Inflación"),

    ("5",         "COSTOS DE PRODUCCIÓN",                                       "Grupo",     "",          "",                       ""),
    ("5.1",       "COSTOS DE FABRICACIÓN (DIRECTOS E INDIRECTOS)",              "Subgrupo",  "",          "",                       "Costo de Producción"),
    ("5.1.01",    "MPD — Harina de Trigo Industrial",                           "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.02",    "MPD — Queso Llanero/Blanco Pasteurizado",                    "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.03",    "MPD — Margarina Industrial",                                 "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.04",    "MPD — Rellenos Mixtos (jamón/pollo/q.crema)",                "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.05",    "MPD — Sal, Especias y Colorantes",                           "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.06",    "MPD — Salsa/Concentrado de Tomate",                          "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.07",    "MPD — Aceite Vegetal",                                       "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.08",    "MPD — Levadura / Especias Masa",                             "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.09",    "MPI — Bolsa MAP con Gas Inerte",                             "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.09.01", "MPI — Etiqueta de Trazabilidad",                             "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.09.02", "MPI — Caja Cartón Corrugado",                                "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.09.03", "MPI — Bolsa Térmica Canal Detal",                            "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.10",    "MOD — Mano de Obra Directa",                                 "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.11",    "CIF — Personal de Apoyo a Producción",                       "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.12",    "CIF — Arrendamiento Planta de Producción",                   "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.13",    "CIF — Electricidad y Combustible (60%)",                     "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.14",    "CIF — Depreciación Equipos de Producción",                   "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.15",    "CIF — Fumigación INSAI/SACS",                                "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.16",    "CIF — Mantenimiento Planta Eléctrica (65 kVA)",              "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.17",    "CIF — Mantenimiento Cava Industrial −18 °C",                 "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.18",    "CIF — EPP y Materiales de Limpieza/Saneam.",                 "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.19",    "CIF — Cadena de Frío — Transporte Refrigerado",              "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.20",    "CIF Aplicados (contrapartida absorción)",                    "Cuenta",    "Acreedora", "Estado de Resultado",    "Costo de Producción"),
    ("5.1.21",    "Variación CIF (Sobre/Subabsorción)",                         "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.1.22",    "Mermas Normales de Producción",                              "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Producción"),
    ("5.2",       "COSTO DE VENTAS",                                            "Subgrupo",  "",          "",                       "Costo de Ventas"),
    ("5.2.01",    "Costo de Ventas — TQ-30/50 Tequeños",                        "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Ventas"),
    ("5.2.02",    "Costo de Ventas — MP-15 Minipizzas",                         "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Ventas"),
    ("5.2.03",    "Costo de Ventas — MF-500 Masa Fácil",                        "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Ventas"),
    ("5.2.04",    "Costo de Ventas — TJ-20 Tequeños Jumbo",                     "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Ventas"),
    ("5.2.05",    "Costo de Ventas — PS-20/30 Pastelitos",                      "Cuenta",    "Deudora",   "Estado de Resultado",    "Costo de Ventas"),

    ("6",         "GASTOS DEL PERÍODO",                                         "Grupo",     "",          "",                       ""),
    ("6.1",       "GASTOS DE VENTAS Y DISTRIBUCIÓN",                            "Subgrupo",  "",          "",                       "Gastos de Ventas"),
    ("6.1.01",    "Sueldos y Salarios — Personal de Ventas",                    "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.1.02",    "Comisiones sobre Ventas",                                    "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.1.03",    "Publicidad y Mercadeo",                                      "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.1.04",    "Fletes y Distribución",                                      "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.1.05",    "Empaques y Materiales de Distribución",                      "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.1.06",    "Combustible — Flota de Distribución",                        "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.1.07",    "Mantenimiento y Reparación de Vehículos",                    "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.1.08",    "Peajes y Viáticos de Distribución",                          "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.1.09",    "Alquiler — Depósito / Centro Distribución",                  "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.1.10",    "Alquiler — Local / Punto de Venta Detal",                    "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos de Ventas"),
    ("6.2",       "GASTOS ADMINISTRATIVOS",                                     "Subgrupo",  "",          "",                       "Gastos Administrativos"),
    ("6.2.01",    "Sueldos y Salarios — Administración",                        "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.02",    "Prestaciones Sociales — Administración",                     "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.03",    "Alquiler Planta de Producción",                              "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.04",    "Servicios Públicos (electricidad, agua, gas)",               "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.05",    "Telefonía e Internet",                                       "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.06",    "Papelería y Útiles de Oficina",                              "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.07",    "Gastos de Representación",                                   "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.08",    "Honorarios Profesionales",                                   "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.09",    "Seguros",                                                    "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.10",    "Depreciación — Activos Administrativos",                     "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.11",    "Amortización — Intangibles",                                 "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.12",    "Gastos Bancarios",                                           "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.13",    "Impuesto Municipal (Patente / IAE)",                         "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.14",    "Multas y Sanciones",                                         "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.15",    "Gastos Varios Administrativos",                              "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.16",    "Impuesto Municipal IAE — Actividad Industrial",              "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.17",    "Vigilancia y Seguridad",                                     "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.18",    "Antigüedad LOTTT (Art. 142)",                                "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.19",    "Intereses sobre Prestaciones Sociales",                      "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.20",    "Contribución Protección Pensiones — 9%",                     "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.21",    "Contribución INCES — 2%",                                    "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.2.22",    "Agua Potable — Planta y Oficinas",                           "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Administrativos"),
    ("6.3",       "GASTOS FINANCIEROS",                                         "Subgrupo",  "",          "",                       "Gastos Financieros"),
    ("6.3.01",    "Intereses sobre Préstamos",                                  "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Financieros"),
    ("6.3.02",    "Comisiones Bancarias",                                       "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Financieros"),
    ("6.3.03",    "Pérdida en Venta de Activos",                                "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Financieros"),
    ("6.3.04",    "IGTF — Gasto no deducible ISLR",                             "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Financieros"),
    ("6.3.05",    "Pérdida en Diferencial Cambiario",                           "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Financieros"),
    ("6.3.06",    "IGTF — Gasto Generado en Compras (Divisas)",                 "Cuenta",    "Deudora",   "Estado de Resultado",    "Gastos Financieros"),
    ("6.4",       "IMPUESTO SOBRE LA RENTA (ISLR)",                             "Subgrupo",  "",          "",                       "ISLR"),
    ("6.4.01",    "ISLR Estimado del Ejercicio",                                "Cuenta",    "Deudora",   "Estado de Resultado",    "ISLR"),
    ("6.5",       "AJUSTE POR INFLACIÓN",                                       "Subgrupo",  "",          "",                       "Ajuste Inflación"),
    ("6.5.01",    "Pérdida Monetaria por Inflación (REI)",                      "Cuenta",    "Deudora",   "Estado de Resultado",    "Ajuste Inflación"),
    ("6.6",       "OTRAS PÉRDIDAS OPERATIVAS",                                  "Subgrupo",  "",          "",                       "Otras Pérdidas Operativas"),
    ("6.6.01",    "Pérdida por Cadena de Frío (daño de inventario)",            "Cuenta",    "Deudora",   "Estado de Resultado",    "Otras Pérdidas Operativas"),

    ("7",         "CUENTAS DE CIERRE",                                          "Grupo",     "",          "",                       ""),
    ("7.1.01",    "Resumen de Pérdidas y Ganancias",                            "Cuenta",    "Deudora",   "Cierre",                 "Cierre"),
]
